### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by schmitt330** [colinbodor/projectton#14]
Hey! 
I love the project and it was working really well but the other day all the prefixes disappeared. The session is still established and it reconnects if I turn it off and on. Are you guys having any issues?

**Comment by colinbodor** [comment]
Hello! thank you for using our service! you should be getting our entire route table now. Looks like a little blip in exabgp. Thank you for letting us know and please reach out in the future as well! We are working on a fix as well.

**Comment by schmitt330** [comment]
Thanks for the quick response. I already see the routes.

**Comment by schmitt330** [comment]
I am seeing the routes down again for a few days now it seems. Let me know if there is a better place to report this to you.

**Comment by colinbodor** [comment]
Hello, we are doing some work to improve our stability, should be back up soon!

**Comment by schmitt330** [comment]
Great thanks!
If there is anything I can do to help contribute to the project let me know, I'm thoroughly invested lol.

**Comment by colinbodor** [comment]
Thanks for the offer! Ill pass it a long to the team. Mostly we are working towards getting more folks using it, so if you know any other networks who might be interested, please feel free to point them our way!

**Comment by screwloose83** [comment]
Hi. I'm interested in using the service. I sent some emails a while back but never got a response.  I have the config in my router but the BGP session never came up. Do you have to register you endpoint ip to make this work? Thanks

**Comment by thepurplebuffalo** [comment]
> 
> 
> Hi. I'm interested in using the service. I sent some emails a while back but never got a response. I have the config in my router but the BGP session never came up. Do you have to register you endpoint ip to make this work? Thanks

No registration needed.  It should just work.  Is the BGP neighborship coming up?

**Comment by screwloose83** [comment]
No it's not. Let me go back and review the config tho.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by thepurplebuffalo** [comment]
OK - that narrows it down a fair bit.  There are two common causes of the neighborship not coming up:

1. eBGP multihop isn't configured or the hopcount is too low.
2. the only route you have to Project TON is through the default route.  Adding a more specific route to Project TON should resolve this.

Hmm... I'm starting to think this might be good information for a troubleshooting guide.

**Comment by screwloose83** [comment]
Ok let me try and come back to you with what I find for your guide. Thanks for the response

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
